<?php

namespace ContainerIdINeeL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginforAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\LoginforAuthenticator' shared autowired service.
     *
     * @return \App\Security\LoginforAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\LoginforAuthenticator'] = new \App\Security\LoginforAuthenticator(($container->services['router'] ?? self::getRouterService($container)));
    }
}
