<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvOEkbc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvOEkbc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFvOEkbc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFvOEkbc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFvOEkbc\App_KernelDevDebugContainer([
    'container.build_hash' => 'FvOEkbc',
    'container.build_id' => '1c328364',
    'container.build_time' => 1706868280,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvOEkbc');
