<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKlFYuYH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKlFYuYH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKlFYuYH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKlFYuYH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKlFYuYH\App_KernelDevDebugContainer([
    'container.build_hash' => 'KlFYuYH',
    'container.build_id' => '0ae368b3',
    'container.build_time' => 1706792969,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKlFYuYH');
